### ISSUE TITLE
update dockerfile

### ISSUE THREAD

**Issue by gdoenlen** [SFXD/trust-bot#4]
The docker files currently assume Java 8 and that we're running an http server... neither of these are true. The file should be updated to run the OpenJDK 11 and not bind to any http port.

the docker image will also need to have access to the database file.

**Comment by Windyo** [comment]
@gdoenlen those docker files ? 
https://github.com/SFXD/trust-bot/tree/master/src/main/java/docker
because if so thy're based off of UBI and I don't know shit about red hat

**Comment by gdoenlen** [comment]
Those are just auto-generated from quarkus when  you make a new project. They don't have to be RH UBI based (i'd probably choose https://www.flatcar-linux.org/). 

The main issue is that Dockerfile.jvm assumes java 8 (this isn't true) and both files bind to 8080. We're not using the http server and lastly I'm not sure where to put the database file/how to bind that to the FS outside the container (currently in dev mode I just write the db file to ~/trust-db).
